version: '3'
services:
#  django:
#    container_name: django
#    build: payment
#    env_file:
#      - .env
#    restart:
#      always
#    ports:
#      - "8000:8000"

  db:
    container_name: postgres_db
    hostname: postgres_db
    image: postgres:15-alpine
    #    volumes:
    #      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES__USER}
      - POSTGRES_PASSWORD=${POSTGRES__PASSWORD}
      - POSTGRES_DB=${POSTGRES__DBNAME}
    ports:
      - "5432:5432"

#volumes:
#  postgres_data: