# Generated by Django 4.1.6 on 2023-02-11 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profile", "0001_initial"),
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_ordered", models.BooleanField(default=False)),
                ("date_added", models.DateTimeField(auto_now=True)),
                ("date_ordered", models.DateTimeField(null=True)),
                (
                    "item",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="item.item",
                    ),
                ),
            ],
            options={
                "db_table": "order_item",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_code", models.CharField(max_length=15)),
                ("is_ordered", models.BooleanField(default=False)),
                ("date_ordered", models.DateTimeField(auto_now=True)),
                ("items", models.ManyToManyField(to="shopping_cart.orderitem")),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "db_table": "order",
            },
        ),
    ]
